"""Fix FK between Event and Tenant

Revision ID: 1bf1f25aab34
Revises: 77dcfeca03e7
Create Date: 2026-03-06 22:04:18.891722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf1f25aab34'
down_revision: Union[str, Sequence[str], None] = '77dcfeca03e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_tenant_id_fkey'), 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(op.f('event_tenant_id_fkey'), 'event', 'event_type', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
