"""Fix back_populates for daily_aggregates

Revision ID: 3b6455dcb73f
Revises: 1bf1f25aab34
Create Date: 2026-03-06 22:15:01.474046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6455dcb73f'
down_revision: Union[str, Sequence[str], None] = '1bf1f25aab34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
