version: "3.9"

services:

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --workers 2
    env_file:
      - .env.docker
    environment:
      PYTHONPATH: /app 
    ports:
      - "8000:8000"
    depends_on:
      - postgres_shard1
      - postgres_shard2
      - redis 

  worker:
    build: .
    command: celery -A worker.app.celery_app worker -l info 
    env_file:
      - .env.docker
    environment:
      PYTHONPATH: /app 
    depends_on:
      - postgres_shard1
      - postgres_shard2
      - redis 

  postgres_shard1:
    image: postgres:16
    env_file:
      - .env.docker
    volumes:
      - postgres_shard1_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s 
      retries: 5

  postgres_shard2:
    image: postgres:16
    env_file:
      - .env.docker
    volumes:
      - postgres_shard2_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s 
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_shard1_data:
  postgres_shard2_data:
